### ISSUE TITLE
composer lock file warning after semantic release

### ISSUE THREAD

**Issue by Jonnx** [ambimax/semantic-release-composer#14]
I am using this plugin in a CI/CD pipeline that tags a version. Everything works fine. Once the version is tagged, we run additional workflows off of the tagged version (tests etc).

There is a warning message displayed when running off of the tagged version.

```
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. It is recommended that you run `composer update` or `composer update <package name>`.
```

Apparently running the command `composer update --lock` before committing the changes generated during the release process after the new version number is set could resolve this issue.

**Comment by Jonnx** [comment]
^ opened a pr to resolve this isse

**Comment by Jonnx** [comment]
Thoughts on getting this merged? If not it's not a problem, I can run off of my own fork.

**Comment by Jonnx** [comment]
if anyone is running into this issue, and wants to use my fork while this pr / issue is awaiting response, you can update you package.json file as follows and you will receive the patched version

```
{
  ...
  "devDependencies": {
      "@ambimax/semantic-release-composer": "jonnx/semantic-release-composer",
      ...
  }
  ...
}
```

Running `yarn upgrade @ambimax/semantic-release-composer` then ensures the latest version is installed on your local machine if you node_modules are already installed locally

**Comment by FabianKoehnen** [comment]
FIxed with https://github.com/ambimax/semantic-release-composer/pull/16
